// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideothequeTcpApp.VideoService.Infrastructure.Persistence;

#nullable disable

namespace VideothequeTcpApp.VideoService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251009022108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VideothequeTcpApp.Models.Domain.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Price = 4.99m,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Price = 5.49m,
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Director = "Lana & Lilly Wachowski",
                            Genre = "Action",
                            Price = 3.99m,
                            Title = "The Matrix",
                            Year = 1999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
